# Change these first
owner: bunt4021 # Your GitHub organization or username, where this repository lives
repo: dubstatus # The name of this repository

sites:
  - name: doubledouble
    url: https://doubledouble.top

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.doubledouble.top
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DoubleDouble Status
  introTitle: "DoubleDouble status page, powered by Upptime."
  introMessage: DoubleDouble status page.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
